services:
  redis:
    image: redis:latest
    container_name: app_redis
    ports:
      - "6382:6379"
    networks:
      - app-network

  app:
    image: php-redis:latest
    container_name: app_php
    volumes:
      - /Users/mitap/www/SEOMonitor:/var/www/html/SEOMonitor
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    networks:
      - app-network
      

networks:
  app-network:
    driver: "bridge"
